# Configures rkt tests at Travis CI (https://travis-ci.org).

language: go
sudo: required
dist: trusty

go:
  - 1.5.4
  - 1.6.3
  - 1.7

env:
  - TARGET=amd64
  - TARGET=arm64

addons:
  apt:
    packages:
    - cpio
    - realpath
    - squashfs-tools
    - build-essential
    - libacl1-dev
    - libsystemd-journal-dev
    - gcc-aarch64-linux-gnu
    - libc6-dev-arm64-cross

install:
  -

script:
 # Build host and fly to ensure we build stage1 init. We don't build everything
 # to avoid downloading large images.
 -      if [ "${TARGET}" == "amd64" ]; then
                ./autogen.sh;
                ./configure --with-stage1-flavors=host,fly --enable-tpm=auto;
                make unit-check manpages bash-completion;
        elif [ "${TARGET}" == "arm64" ]; then
                eval "$(GIMME_ARCH=${TARGET} GIMME_CGO_ENABLED=1 ./gimme.local ${TRAVIS_GO_VERSION})";
                ./autogen.sh;
                ./configure --host=aarch64-linux-gnu --with-stage1-flavors=host,fly --enable-tpm=auto;
                make V=2;
        fi
