# Configures rkt tests at Travis CI (https://travis-ci.org).

language: go

go:
 - 1.4

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y cpio realpath squashfs-tools
 - sudo apt-get install -y build-essential
 - sudo apt-get install -y libcapture-tiny-perl

install:
 - go get golang.org/x/tools/cmd/cover
 - go get golang.org/x/tools/cmd/vet

script:
 - ./autogen.sh
 - ./configure --with-stage1=none
 - make check
